// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7AMAdTHolvxLahnLaViaJXw7aBkArtzs',
    appId: '1:406920164086:web:0839e6f71e4d37ce7f72d7',
    messagingSenderId: '406920164086',
    projectId: 'biblioshare-262ba',
    authDomain: 'biblioshare-262ba.firebaseapp.com',
    storageBucket: 'biblioshare-262ba.firebasestorage.app',
    measurementId: 'G-V1BDJPTYD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFIwL-tdY5fUos4JFJpcl97yAzP2Kqpqg',
    appId: '1:406920164086:android:8948ee2cb39cf95c7f72d7',
    messagingSenderId: '406920164086',
    projectId: 'biblioshare-262ba',
    storageBucket: 'biblioshare-262ba.firebasestorage.app',
  );

}